"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "id" | "en"

type Translations = {
  [key: string]: {
    id: string
    en: string
  }
}

const translations: Translations = {
  // Auth
  "auth.welcome": { id: "Selamat Datang Kembali", en: "Welcome Back" },
  "auth.subtitle": { id: "Masuk ke akun Carubra Anda", en: "Sign in to your Carubra account" },
  "auth.email": { id: "Email", en: "Email" },
  "auth.emailPlaceholder": { id: "contoh@carubra.id", en: "you@example.com" },
  "auth.password": { id: "Kata Sandi", en: "Password" },
  "auth.passwordPlaceholder": { id: "********", en: "********" },
  "auth.login": { id: "Masuk", en: "Sign In" },
  "auth.noAccount": { id: "Belum punya akun?", en: "Don't have an account?" },
  "auth.register": { id: "Daftar", en: "Register" },
  "auth.registerSubtitle": { id: "Buat akun baru untuk mulai menggunakan Carubra.", en: "Create a new account to start using Carubra." },
  "auth.confirmPassword": { id: "Konfirmasi Kata Sandi", en: "Confirm Password" },
  "auth.passwordMismatch": { id: "Kata sandi tidak cocok.", en: "Passwords do not match." },
  "auth.registerError": { id: "Gagal mendaftar. Silakan coba lagi.", en: "Registration failed. Please try again." },
  "auth.alreadyHaveAccount": { id: "Sudah punya akun?", en: "Already have an account?" },

  // Home / Login page
  "home.agentMarketing": { id: "Agent Marketing", en: "Agent Marketing" },
  "home.whatsappCta": { id: "Hai, temui aku dan coba di WA", en: "Hi, meet me and try on WhatsApp" },

  // Blocked page
  "blocked.title": { id: "Akun Anda Diblokir", en: "Account Blocked" },
  "blocked.description": { id: "Mohon maaf, akun Anda saat ini tidak dapat diakses. Silakan daftar ulang dengan email baru untuk menggunakan kembali layanan.", en: "Sorry, your account is currently inaccessible. Please register again with a new email to use the service." },
  "blocked.registerAgain": { id: "Daftar Ulang", en: "Register Again" },
  "blocked.backToLogin": { id: "Kembali ke Halaman Login", en: "Back to Login" },

  // Header
  "header.coins": { id: "Koin", en: "Coins" },

  // Navigation
  "nav.profile": { id: "Profil", en: "Profile" },
  "nav.member": { id: "Membership", en: "Membership" },
  "nav.videoAi": { id: "Video AI", en: "Video AI" },
  "nav.imageAi": { id: "Image AI", en: "Image AI" },
  "nav.contentAnalytics": { id: "Analitik Konten", en: "Content Analytics" },
  "nav.autoUpload": { id: "Upload Otomatis", en: "Auto Upload" },
  "nav.dashboard": { id: "Dashboard", en: "Dashboard" },
  "nav.adminDashboard": { id: "Dashboard", en: "Dashboard" },
  "nav.userManagement": { id: "Manajemen User", en: "User Management" },
  "nav.membershipTransactions": { id: "Membership & Transaksi", en: "Membership & Transactions" },
  "nav.contentManagement": { id: "Manajemen Konten", en: "Content Management" },
  "nav.coinPricing": { id: "Koin & Pricing", en: "Coin & Pricing" },
  "nav.systemLogs": { id: "Pengaturan Sistem & Log", en: "System Settings & Logs" },
  "nav.devDocs": { id: "Docs Dev", en: "Dev Docs" },
  "nav.logout": { id: "Keluar", en: "Logout" },
  "nav.indonesia": { id: "Indonesia", en: "Indonesia" },
  "nav.english": { id: "English", en: "English" },
  "nav.langEn": { id: "EN", en: "ID" },
  "nav.langId": { id: "ID", en: "EN" },

  // Profile
  "profile.title": { id: "Profil Pengguna", en: "User Profile" },
  "profile.name": { id: "Nama Lengkap", en: "Full Name" },
  "profile.phone": { id: "Nomor Telepon", en: "Phone Number" },
  "profile.save": { id: "Simpan Perubahan", en: "Save Changes" },
  "profile.username": { id: "Username", en: "Username" },
  "profile.role": { id: "Role", en: "Role" },
  "profile.membershipOrder": { id: "Nomor Pesanan Membership", en: "Membership Order Number" },
  "profile.totalVideos": { id: "Total Video Dibuat", en: "Total Videos Created" },
  "profile.connectedSocialAccounts": { id: "Total Sosial Media Terhubung", en: "Total Connected Social Accounts" },
  "profile.passwordInfo": { id: "Informasi Ganti Password", en: "Password Change Info" },
  "profile.changePassword": { id: "Ubah Kata Sandi", en: "Change Password" },
  "profile.cancelChangePassword": { id: "Batal", en: "Cancel" },
  "profile.submitPasswordChange": { id: "Simpan Password", en: "Save Password" },
  "profile.currentPassword": { id: "Kata Sandi Saat Ini", en: "Current Password" },
  "profile.currentPasswordPlaceholder": { id: "Masukkan kata sandi saat ini", en: "Enter current password" },
  "profile.newPassword": { id: "Kata Sandi Baru", en: "New Password" },
  "profile.newPasswordPlaceholder": { id: "Masukkan kata sandi baru", en: "Enter new password" },
  "profile.confirmNewPassword": { id: "Konfirmasi Kata Sandi Baru", en: "Confirm New Password" },
  "profile.confirmNewPasswordPlaceholder": { id: "Konfirmasi kata sandi baru", en: "Confirm your new password" },
  "profile.fillAllPasswordFields": { id: "Silakan isi semua kolom password.", en: "Please fill all password fields." },
  "profile.passwordChangeFailed": { id: "Gagal mengubah password. Coba lagi.", en: "Failed to change password. Please try again." },
  "profile.passwordChangedSuccess": { id: "Password berhasil diubah.", en: "Password updated successfully." },
  "profile.passwordLimitInfo": { id: "Perubahan password dapat dilakukan hingga {count} kali.", en: "You may change your password up to {count} times." },

  // Dashboard
  "dashboard.welcomeBadge": { id: "Selamat datang di Carubra", en: "Welcome to Carubra" },
  "dashboard.greeting": { id: "Hai, {name}.", en: "Hi, {name}." },
  "dashboard.description": { id: "Platform marketing cerdas untuk konten sosial media kamu. Yuk cek jadwal konten dan lanjutkan ide kreatifmu dengan AI image/video.", en: "Smart marketing platform for your social media content. Check your content schedule and continue your creative ideas with AI image/video." },
  "dashboard.scheduleContent": { id: "Atur Jadwal Konten", en: "Schedule Content" },
  "dashboard.createAiContent": { id: "Buat Konten AI", en: "Create AI Content" },
  "dashboard.contentSummary": { id: "Ringkasan Konten", en: "Content Summary" },
  "dashboard.scheduledCount": { id: "{count} konten sudah dijadwalkan", en: "{count} contents scheduled" },
  "dashboard.noScheduled": { id: "Belum ada konten terjadwalkan", en: "No scheduled content" },
  "dashboard.loadingSchedule": { id: "Memuat jadwal...", en: "Loading schedule..." },
  "dashboard.emptySchedule": { id: "Belum ada konten terjadwalkan. Bikin jadwal atau gunakan fitur Auto Upload sekarang.", en: "No scheduled content yet. Create a schedule or use Auto Upload now." },
  "dashboard.defaultCaption": { id: "Konten terjadwal", en: "Scheduled content" },
  "dashboard.connectionStatus": { id: "Status Koneksi", en: "Connection Status" },
  "dashboard.connectionCount": { id: "{count} akun sudah terhubung", en: "{count} accounts connected" },
  "dashboard.noConnection": { id: "Belum ada akun sosial yang terhubung", en: "No social accounts connected" },
  "dashboard.connectedAccounts": { id: "Akun sosial yang terhubung", en: "Connected social accounts" },
  "dashboard.connectedAccountsDesc": { id: "Lihat Auto Upload untuk kelola akun dan koneksi lebih lanjut.", en: "Go to Auto Upload to manage accounts and connections." },
  "dashboard.connectionEmptyDesc": { id: "Hubungkan Instagram, Facebook, TikTok, dan lainnya agar jadwal bisa dikirim otomatis.", en: "Connect Instagram, Facebook, TikTok, and more to auto-send your schedule." },
  "dashboard.manageConnections": { id: "Kelola Koneksi", en: "Manage Connections" },
  "dashboard.reminders": { id: "Pengingat", en: "Reminders" },
  "dashboard.remindersSubtitle": { id: "Kontenmu siap ditinjau", en: "Your content is ready for review" },
  "dashboard.reminder1": { id: "Pastikan deskripsi, hashtag, dan tipe postingan sudah sesuai sebelum jadwal dijalankan.", en: "Make sure descriptions, hashtags, and post types are correct before the schedule runs." },
  "dashboard.reminder2": { id: "Ingin lebih cepat? Gunakan fitur Image AI atau Video AI untuk konten berkualitas dengan cepat.", en: "Want to go faster? Use Image AI or Video AI for quality content quickly." },
  "dashboard.reminder3": { id: "Semakin lengkap koneksi sosial, semakin nyaman penjadwalan otomatis.", en: "The more social connections, the smoother your auto-scheduling." },
  "dashboard.fetchError": { id: "Gagal memuat data", en: "Failed to load data" },
  "dashboard.loadError": { id: "Terjadi kesalahan saat memuat data: {error}", en: "An error occurred while loading data: {error}" },

  // Member
  "member.title": { id: "Membership", en: "Membership" },
  "member.subtitle": { id: "Pilih paket koin membership yang paling sesuai dengan kebutuhan konten Anda.", en: "Choose the membership coin package that best fits your content needs." },
  "member.packagePrice": { id: "Harga Paket", en: "Package Price" },
  "member.buy": { id: "Beli", en: "Buy" },
  "member.recentTransactions": { id: "Daftar Transaksi Terakhir", en: "Recent Transactions" },
  "member.transactionDescription": { id: "Lihat status pembayaran dan invoice pembelian membership Anda.", en: "View your membership payment status and purchase invoices." },
  "member.invoice": { id: "Invoice", en: "Invoice" },
  "member.date": { id: "Tanggal", en: "Date" },
  "member.package": { id: "Paket", en: "Package" },
  "member.price": { id: "Harga", en: "Price" },
  "member.paymentProof": { id: "Bukti Pembayaran", en: "Payment Proof" },
  "member.viewProof": { id: "Lihat Bukti", en: "View Proof" },
  "member.selectedPackage": { id: "Paket Terpilih:", en: "Selected Package:" },
  "member.status.completed": { id: "Selesai", en: "Completed" },
  "member.status.pending": { id: "Pending", en: "Pending" },
  "member.status.failed": { id: "Gagal", en: "Failed" },
  "member.balanceTitle": { id: "Saldo Token", en: "Token Balance" },
  "member.balanceDescription": { id: "Gunakan token untuk upload otomatis, analisis konten, dan promosi.", en: "Use tokens for auto uploads, content analysis, and promotion." },
  "member.statusLabel": { id: "Status", en: "Status" },
  "member.lastTopup": { id: "Last top-up", en: "Last top-up" },
  "member.topUpNow": { id: "Top Up Sekarang", en: "Top Up Now" },
  "member.viewHistory": { id: "Lihat Riwayat", en: "View History" },
  "member.loadingPackages": { id: "Memuat paket…", en: "Loading packages…" },
  "member.noPackages": { id: "Belum ada paket tersedia.", en: "No packages available." },
  "member.processing": { id: "Memproses…", en: "Processing…" },
  "member.loadingTransactions": { id: "Memuat riwayat transaksi…", en: "Loading transaction history…" },
  "member.noTransactions": { id: "Belum ada transaksi.", en: "No transactions yet." },
  "member.emptyTransactionsDescription": { id: "Riwayat transaksi akan muncul setelah Anda melakukan pembayaran.", en: "Transaction history will appear after you complete a payment." },
  "member.invoiceExpired": { id: "Invoice kedaluwarsa.", en: "Invoice expired." },
  "member.payNow": { id: "Bayar Sekarang", en: "Pay Now" },
  "member.packageLabel": { id: "Paket", en: "Package" },
  "member.tokenLabel": { id: "Token", en: "Tokens" },
  "member.priceLabel": { id: "Harga", en: "Price" },
  "member.token": { id: "Token", en: "Tokens" },
  "member.later": { id: "Nanti saja", en: "Later" },
  "member.securePayment": { id: "Pembayaran Aman", en: "Secure Payment" },
  "member.invoiceWillExpireIn": { id: "Invoice ini akan kedaluwarsa dalam {countdown}", en: "This invoice will expire in {countdown}" },
  "member.minutes": { id: "mnt", en: "min" },
  "member.seconds": { id: "dtk", en: "sec" },
  "member.copy": { id: "Salin", en: "Copy" },
  "member.paymentMethods": { id: "Metode Pembayaran", en: "Payment Methods" },
  "member.noTokens": { id: "Tidak ada token", en: "No tokens" },
  "member.viewPackages": { id: "Lihat Paket", en: "View Packages" },
  "member.topUp": { id: "Top Up", en: "Top Up" },
  "member.topUpMembership": { id: "Top Up Membership", en: "Top Up Membership" },
  "member.success": { id: "Berhasil", en: "Success" },
  "member.failed": { id: "Gagal", en: "Failed" },
  "member.refunded": { id: "Dikembalikan", en: "Refunded" },
  "member.balance": { id: "Saldo Token", en: "Token Balance" },
  "member.totalTransactions": { id: "Total Transaksi", en: "Total Transactions" },
  "member.packagePurchased": { id: "Paket Berhasil Dibeli", en: "Package Purchased" },
  "member.membershipPackage": { id: "Paket Membership", en: "Membership Package" },
  "member.paymentDate": { id: "Tanggal Pembayaran", en: "Payment Date" },
  "member.invoiceId": { id: "Invoice ID", en: "Invoice ID" },
  "member.amount": { id: "Jumlah", en: "Amount" },
  "member.paymentMethod": { id: "Metode Pembayaran", en: "Payment Method" },
  "member.status": { id: "Status", en: "Status" },
  "member.transactionHistory": { id: "Riwayat Transaksi", en: "Transaction History" },
  "member.paidAt": { id: "Dibayar", en: "Paid At" },
  "member.transactionCount": { id: "Menampilkan {count} transaksi", en: "Showing {count} transactions" },
  "member.welcomeModalTitle": { id: "Paket Token", en: "Token Packages" },
  "member.welcomeModalHeading": { id: "Paket token untuk semua kebutuhan Anda", en: "Token packages for all your needs" },
  "member.welcomeModalBody": { id: "Dengan paket token kami, Anda mendapatkan akses instan ke berbagai fitur premium. Token dapat digunakan untuk meningkatkan pengalaman Anda, membuka fitur eksklusif, dan mendapatkan dukungan prioritas. Pilih paket yang sesuai dengan kebutuhan Anda dan nikmati manfaatnya sekarang!", en: "With our token packages, you get instant access to various premium features. Tokens can be used to enhance your experience, unlock exclusive features, and get priority support. Choose the package that fits your needs and enjoy the benefits now!" },
  "member.active": { id: "Aktif", en: "Active" },
  "member.invoiceExpiredOn": { id: "Invoice kedaluwarsa pada {date}.", en: "Invoice expired on {date}." },
  "member.createNewInvoice": { id: "Buat Invoice Baru", en: "Create New Invoice" },
  "member.contactAdmin": { id: "Hubungi admin:", en: "Contact admin:" },
  "member.paymentComplete": { id: "Pembayaran selesai ✓", en: "Payment complete ✓" },
  "member.close": { id: "Tutup", en: "Close" },
  "member.unitPrice": { id: "{price} / token", en: "{price} / token" },
  "member.pendingPayment": { id: "Menunggu Pembayaran", en: "Awaiting Payment" },
  "member.createInvoiceFailed": { id: "Gagal membuat invoice. Coba lagi.", en: "Failed to create invoice. Try again." },
  "member.paymentAlreadyComplete": { id: "Pembayaran sudah selesai.", en: "Payment already completed." },
  "member.invoiceUnavailable": { id: "Invoice tidak dapat digunakan.", en: "Invoice is unavailable." },
  "member.openInvoiceFailed": { id: "Gagal membuka invoice.", en: "Failed to open invoice." },
  "member.dibayar": { id: "Dibayar: ", en: "Paid: " },
  "member.unknownDate": { id: "tanggal tidak diketahui", en: "unknown date" },
  "member.orderId": { id: "Order ID: {id}", en: "Order ID: {id}" },

  // Invoice Detail
  "invoice.title": { id: "Invoice", en: "Invoice" },
  "invoice.loading": { id: "Memuat invoice…", en: "Loading invoice…" },
  "invoice.notFound": { id: "Invoice tidak ditemukan", en: "Invoice not found" },
  "invoice.backToDashboard": { id: "Kembali ke Dashboard", en: "Back to Dashboard" },
  "invoice.back": { id: "← Kembali", en: "← Back" },
  "invoice.package": { id: "Paket", en: "Package" },
  "invoice.token": { id: "Token", en: "Token" },
  "invoice.total": { id: "Total", en: "Total" },
  "invoice.status": { id: "Status", en: "Status" },
  "invoice.created": { id: "Dibuat", en: "Created" },
  "invoice.paid": { id: "Dibayar", en: "Paid" },
  "invoice.downloadPdf": { id: "Download PDF", en: "Download PDF" },
  "invoice.expiredTitle": { id: "Invoice Kedaluwarsa", en: "Invoice Expired" },
  "invoice.expiredDescription": { id: "Invoice pembayaran ini telah kedaluwarsa dan tidak dapat digunakan lagi. Apakah Anda ingin membuat invoice baru dengan paket yang sama?", en: "This payment invoice has expired and can no longer be used. Would you like to create a new invoice with the same package?" },
  "invoice.cancel": { id: "Batal", en: "Cancel" },
  "invoice.createNew": { id: "Buat Invoice Baru", en: "Create New Invoice" },
  "invoice.processing": { id: "Memproses...", en: "Processing..." },
  "invoice.failedTitle": { id: "Gagal", en: "Failed" },
  "invoice.newInvoiceFailed": { id: "Gagal membuat invoice baru. Silakan coba lagi.", en: "Failed to create a new invoice. Please try again." },
  "invoice.lunas": { id: "LUNAS", en: "PAID" },
  "invoice.menunggu": { id: "Menunggu Pembayaran", en: "Awaiting Payment" },
  "invoice.gagal": { id: "GAGAL", en: "FAILED" },
  "invoice.kedaluwarsa": { id: "KEDALUWARSA", en: "EXPIRED" },

  // Payment Success
  "paymentSuccess.title": { id: "Pembayaran Berhasil", en: "Payment Successful" },
  "paymentSuccess.heading": { id: "Token Sudah Masuk!", en: "Tokens Added!" },
  "paymentSuccess.description": { id: "Transaksi kamu telah diproses. Token siap digunakan untuk membuat konten AI.", en: "Your transaction has been processed. Tokens are ready to use for creating AI content." },
  "paymentSuccess.orderId": { id: "Order ID", en: "Order ID" },
  "paymentSuccess.yourBalance": { id: "Saldo Token Kamu Sekarang", en: "Your Token Balance Now" },
  "paymentSuccess.loadingBalance": { id: "Memuat saldo token…", en: "Loading token balance…" },
  "paymentSuccess.dashboard": { id: "Dashboard", en: "Dashboard" },
  "paymentSuccess.viewTokens": { id: "Lihat Token", en: "View Tokens" },
  "paymentSuccess.autoRedirect": { id: "Otomatis ke halaman token dalam {seconds}s", en: "Auto-redirecting to tokens in {seconds}s" },

  // Admin
  "admin.console": { id: "Admin Console", en: "Admin Console" },
  "admin.dashboardTitle": { id: "Superadmin Dashboard", en: "Superadmin Dashboard" },
  "admin.dashboardDescription": { id: "Kelola pengguna, isi konten, dan pantau kesehatan platform secara cepat.", en: "Manage users, content, and monitor platform health at a glance." },
  "admin.signedInAs": { id: "Signed in as", en: "Signed in as" },
  "admin.totalUsers": { id: "Total Pengguna", en: "Total Users" },
  "admin.activeAdmins": { id: "Admin Aktif", en: "Active Admins" },
  "admin.bannedUsers": { id: "Pengguna Terblokir", en: "Banned Users" },
  "admin.activeMembership": { id: "Membership Aktif", en: "Active Membership" },
  "admin.totalCoins": { id: "Total Koin", en: "Total Coins" },
  "admin.savedContent": { id: "Konten Tersimpan", en: "Saved Content" },
  "admin.systemHealth": { id: "Kesehatan Sistem", en: "System Health" },
  "admin.systemHealthDesc": { id: "Semua layanan platform berjalan normal.", en: "All platform services are running normally." },
  "admin.authentication": { id: "Autentikasi", en: "Authentication" },
  "admin.database": { id: "Database", en: "Database" },
  "admin.stats": { id: "Statistik", en: "Statistics" },
  "admin.performanceSummary": { id: "Ringkasan Kinerja", en: "Performance Summary" },
  "admin.aiMonitor": { id: "Monitor AI", en: "AI Monitor" },
  "admin.aiUsageTitle": { id: "Penggunaan AI Terakhir", en: "Latest AI Usage" },
  "admin.totalAiEvents": { id: "Total Event AI", en: "Total AI Events" },
  "admin.totalTokensUsed": { id: "Total Token", en: "Total Tokens" },
  "admin.lastQuota": { id: "Kuota Terakhir", en: "Last Quota" },
  "admin.lastUsed": { id: "Terakhir Dipakai", en: "Last Used" },
  "admin.noAiData": { id: "Belum ada data penggunaan AI", en: "No AI usage data yet" },
  "admin.monthlyTrend": { id: "Tren Bulanan", en: "Monthly Trend" },
  "admin.monthlyAiUsage": { id: "Penggunaan AI Bulanan", en: "Monthly AI Usage" },
  "admin.noTrendData": { id: "Belum ada data tren bulanan", en: "No monthly trend data yet" },
  "admin.deleteContent": { id: "Hapus Konten", en: "Delete Content" },
  "admin.confirmDeleteContent": { id: "Hapus konten ini secara permanen?", en: "Permanently delete this content?" },
  "admin.cancel": { id: "Batal", en: "Cancel" },
  "admin.confirmDelete": { id: "Ya, Hapus", en: "Yes, Delete" },
  "admin.loadingAdmin": { id: "Memuat halaman admin…", en: "Loading admin page…" },
  "admin.accessDenied": { id: "Akses ditolak. Halaman ini hanya untuk admin.", en: "Access denied. This page is for admins only." },
  "admin.fetchError": { id: "Tidak dapat memuat data admin", en: "Unable to load admin data" },
  "admin.invoiceTransactionsTitle": { id: "Invoice & Transaksi", en: "Invoices & Transactions" },
  "admin.invoiceTransactionsDescription": { id: "Kelola dan pantau seluruh transaksi pembelian token.", en: "Manage and monitor all token purchase transactions." },
  "admin.exportCsv": { id: "Export CSV", en: "Export CSV" },
  "admin.exporting": { id: "Mengekspor…", en: "Exporting…" },
  "admin.search": { id: "Cari", en: "Search" },
  "admin.searchPlaceholder": { id: "Invoice ID / User ID / Paket", en: "Invoice ID / User ID / Package" },
  "admin.status": { id: "Status", en: "Status" },
  "admin.statusAll": { id: "Semua", en: "All" },
  "admin.statusSuccess": { id: "Berhasil", en: "Success" },
  "admin.statusPending": { id: "Menunggu", en: "Pending" },
  "admin.statusFailed": { id: "Gagal", en: "Failed" },
  "admin.statusExpired": { id: "Kedaluwarsa", en: "Expired" },
  "admin.refunded": { id: "Dikembalikan", en: "Refunded" },
  "admin.dateFrom": { id: "Dari", en: "From" },
  "admin.dateTo": { id: "Sampai", en: "To" },
  "admin.reset": { id: "Reset", en: "Reset" },
  "admin.revenue": { id: "Pendapatan", en: "Revenue" },
  "admin.successful": { id: "berhasil", en: "successful" },
  "admin.displayed": { id: "Ditampilkan", en: "Displayed" },
  "admin.ofTotal": { id: "dari {count} total", en: "of {count} total" },
  "admin.waiting": { id: "Menunggu", en: "Waiting" },
  "admin.failed": { id: "Gagal", en: "Failed" },
  "admin.exportInvoiceId": { id: "Invoice ID", en: "Invoice ID" },
  "admin.exportUserId": { id: "User ID", en: "User ID" },
  "admin.exportPackage": { id: "Paket", en: "Package" },
  "admin.exportToken": { id: "Token", en: "Token" },
  "admin.exportAmount": { id: "Amount (IDR)", en: "Amount (IDR)" },
  "admin.exportMethod": { id: "Metode", en: "Method" },
  "admin.exportStatus": { id: "Status", en: "Status" },
  "admin.exportCreatedAt": { id: "Tanggal Buat", en: "Created At" },
  "admin.exportPaidAt": { id: "Tanggal Bayar", en: "Paid At" },
  "admin.tokensSold": { id: "Token Terjual", en: "Tokens Sold" },
  "admin.transactionsPending": { id: "transaksi pending", en: "pending transactions" },
  "admin.failedExpired": { id: "Gagal / Expired", en: "Failed / Expired" },
  "admin.expired": { id: "Kedaluwarsa", en: "Expired" },
  "admin.applyFilters": { id: "Terapkan Filter", en: "Apply Filters" },
  "admin.loadingTransactions": { id: "Memuat transaksi…", en: "Loading transactions…" },
  "admin.noTransactions": { id: "Tidak ada transaksi", en: "No transactions" },
  "admin.tryDifferentFilter": { id: "Coba ubah filter.", en: "Try changing the filter." },
  "admin.package": { id: "Paket", en: "Package" },
  "admin.token": { id: "Token", en: "Token" },
  "admin.amount": { id: "Amount", en: "Amount" },
  "admin.userId": { id: "User ID", en: "User ID" },
  "admin.dibayar": { id: "Dibayar: ", en: "Paid: " },
  "admin.openInvoice": { id: "Buka Invoice", en: "Open Invoice" },
  "admin.paymentComplete": { id: "Pembayaran sudah selesai.", en: "Payment already completed." },
  "admin.invoiceUnavailable": { id: "Invoice tidak dapat dibuka.", en: "Invoice cannot be opened." },
  "admin.openInvoiceFailed": { id: "Gagal membuka invoice.", en: "Failed to open invoice." },
  "admin.warning": { id: "Peringatan", en: "Warning" },
  "admin.close": { id: "Tutup", en: "Close" },
  "admin.transactionCount": { id: "Menampilkan {count} transaksi", en: "Showing {count} transactions" },
  "admin.fromDate": { id: "Dari Tanggal", en: "From Date" },
  "admin.toDate": { id: "Sampai Tanggal", en: "To Date" },
  "admin.loadingData": { id: "Memuat data transaksi…", en: "Loading transaction data…" },
  "admin.noTransactionsFilter": { id: "Tidak ada transaksi", en: "No transactions" },
  "admin.tryChangeFilter": { id: "Coba ubah filter atau periode yang dipilih.", en: "Try changing the filter or selected period." },
  "admin.orderId": { id: "Order ID", en: "Order ID" },
  "admin.user": { id: "User", en: "User" },
  "admin.action": { id: "Aksi", en: "Action" },
  "admin.viewInvoice": { id: "Lihat Invoice", en: "View Invoice" },
  "admin.invoice": { id: "Invoice →", en: "Invoice →" },

  // Admin Users
  "adminUsers.title": { id: "Manajemen User", en: "User Management" },
  "adminUsers.description": { id: "Lihat semua pengguna, role, dan status blokir secara terpusat.", en: "View all users, roles, and ban status in one place." },
  "adminUsers.loading": { id: "Memuat pengguna...", en: "Loading users..." },
  "adminUsers.loadError": { id: "Tidak dapat memuat pengguna", en: "Unable to load users" },
  "adminUsers.searchPlaceholder": { id: "Cari email, nama, role...", en: "Search email, name, role..." },
  "adminUsers.reload": { id: "Muat Ulang", en: "Reload" },
  "adminUsers.email": { id: "Email", en: "Email" },
  "adminUsers.name": { id: "Nama", en: "Name" },
  "adminUsers.role": { id: "Role", en: "Role" },
  "adminUsers.status": { id: "Status", en: "Status" },
  "adminUsers.coins": { id: "Koin", en: "Coins" },
  "adminUsers.actions": { id: "Aksi", en: "Actions" },
  "adminUsers.banned": { id: "Diblokir", en: "Banned" },
  "adminUsers.active": { id: "Aktif", en: "Active" },
  "adminUsers.noResults": { id: "Tidak ada pengguna yang cocok.", en: "No matching users found." },
  "adminUsers.editRole": { id: "Role", en: "Role" },
  "adminUsers.editCoins": { id: "Koin", en: "Coins" },
  "adminUsers.ban": { id: "Ban", en: "Ban" },
  "adminUsers.unban": { id: "Unban", en: "Unban" },
  "adminUsers.resetPw": { id: "Reset PW", en: "Reset PW" },
  "adminUsers.changeRoleTitle": { id: "Ubah Role Pengguna", en: "Change User Role" },
  "adminUsers.currentRole": { id: "Role saat ini", en: "Current role" },
  "adminUsers.cancel": { id: "Batal", en: "Cancel" },
  "adminUsers.saving": { id: "Menyimpan...", en: "Saving..." },
  "adminUsers.saveChanges": { id: "Simpan Perubahan", en: "Save Changes" },
  "adminUsers.changeCoinsTitle": { id: "Ubah Saldo Koin", en: "Change Coin Balance" },
  "adminUsers.coinAmount": { id: "Jumlah Koin", en: "Coin Amount" },
  "adminUsers.coinPlaceholder": { id: "Masukkan jumlah koin", en: "Enter coin amount" },
  "adminUsers.currentBalance": { id: "Saldo saat ini: {coins} koin", en: "Current balance: {coins} coins" },
  "adminUsers.invalidCoins": { id: "Nilai koin tidak valid", en: "Invalid coin value" },
  "adminUsers.resetPasswordTitle": { id: "Reset Kata Sandi", en: "Reset Password" },
  "adminUsers.resetPasswordDescription": { id: "Masukkan kata sandi baru untuk {email}", en: "Enter a new password for {email}" },
  "adminUsers.newPasswordPlaceholder": { id: "Kata sandi baru", en: "New password" },
  "adminUsers.save": { id: "Simpan", en: "Save" },
  "adminUsers.confirmTitle": { id: "Konfirmasi", en: "Confirmation" },
  "adminUsers.confirmAction": { id: "Apakah Anda yakin ingin {action} {email}?", en: "Are you sure you want to {action} {email}?" },
  "adminUsers.yesProceed": { id: "Ya, Lanjutkan", en: "Yes, Proceed" },
  "adminUsers.banAction": { id: "blokir", en: "ban" },
  "adminUsers.unbanAction": { id: "batalkan blokir", en: "unban" },

  // Admin Pricing
  "adminPricing.title": { id: "Manajemen Koin & Pricing", en: "Coin & Pricing Management" },
  "adminPricing.description": { id: "Kelola paket koin dan harga yang tersedia untuk pengguna.", en: "Manage coin packages and prices available to users." },
  "adminPricing.loading": { id: "Memuat pricing...", en: "Loading pricing..." },
  "adminPricing.loadError": { id: "Tidak dapat memuat paket", en: "Unable to load packages" },
  "adminPricing.coinPackages": { id: "Paket Koin", en: "Coin Packages" },
  "adminPricing.activePackages": { id: "{count} paket aktif", en: "{count} active packages" },
  "adminPricing.addPackage": { id: "Tambah Paket", en: "Add Package" },
  "adminPricing.loadingPackages": { id: "Memuat paket…", en: "Loading packages…" },
  "adminPricing.noPackages": { id: "Belum ada paket", en: "No packages yet" },
  "adminPricing.noPackagesDesc": { id: "Tambahkan paket pertama untuk mulai menjual token ke pengguna.", en: "Add your first package to start selling tokens to users." },
  "adminPricing.addNow": { id: "Tambah Sekarang", en: "Add Now" },
  "adminPricing.edit": { id: "Edit", en: "Edit" },
  "adminPricing.delete": { id: "Hapus", en: "Delete" },
  "adminPricing.tokens": { id: "{coins} token", en: "{coins} tokens" },
  "adminPricing.footerNote": { id: "Paket disimpan ke Supabase melalui API admin. Gunakan halaman Membership untuk melihat ringkasan transaksi.", en: "Packages are saved to Supabase via the admin API. Use the Membership page to view transaction summaries." },
  "adminPricing.confirmLabel": { id: "Konfirmasi", en: "Confirmation" },
  "adminPricing.newPackage": { id: "Paket Baru", en: "New Package" },
  "adminPricing.editPackage": { id: "Edit Paket", en: "Edit Package" },
  "adminPricing.deleteTitle": { id: "Hapus Paket?", en: "Delete Package?" },
  "adminPricing.addTokenPackage": { id: "Tambah Paket Token", en: "Add Token Package" },
  "adminPricing.deleteConfirm": { id: "Paket {name} ({coins} token, {price}) akan dihapus permanen. Tindakan ini tidak dapat dibatalkan.", en: "Package {name} ({coins} tokens, {price}) will be permanently deleted. This action cannot be undone." },
  "adminPricing.packageName": { id: "Nama Paket", en: "Package Name" },
  "adminPricing.packageNamePlaceholder": { id: "Contoh: Paket Starter", en: "Example: Starter Package" },
  "adminPricing.tokenAmount": { id: "Jumlah Token", en: "Token Amount" },
  "adminPricing.tokenPlaceholder": { id: "100", en: "100" },
  "adminPricing.price": { id: "Harga", en: "Price" },
  "adminPricing.pricePlaceholder": { id: "Rp 50.000", en: "Rp 50,000" },
  "adminPricing.descriptionOptional": { id: "(opsional)", en: "(optional)" },
  "adminPricing.descriptionPlaceholder": { id: "Cocok untuk pengguna baru…", en: "Great for new users..." },
  "adminPricing.nameRequired": { id: "Nama paket wajib diisi.", en: "Package name is required." },
  "adminPricing.coinsRequired": { id: "Jumlah token harus angka positif.", en: "Token amount must be a positive number." },
  "adminPricing.priceRequired": { id: "Harga wajib diisi.", en: "Price is required." },
  "adminPricing.deleting": { id: "Menghapus…", en: "Deleting..." },
  "adminPricing.saving": { id: "Menyimpan…", en: "Saving..." },
  "adminPricing.updating": { id: "Mengupdate…", en: "Updating..." },
  "adminPricing.yesDelete": { id: "Ya, Hapus", en: "Yes, Delete" },
  "adminPricing.savePackage": { id: "Simpan Paket", en: "Save Package" },
  "adminPricing.saveChanges": { id: "Simpan Perubahan", en: "Save Changes" },
  "adminPricing.cancel": { id: "Batal", en: "Cancel" },

  // Admin Content
  "adminContent.title": { id: "Manajemen Konten", en: "Content Management" },
  "adminContent.description": { id: "Lihat konten yang dihasilkan dan kelola riwayatnya di sini.", en: "View generated content and manage its history here." },
  "adminContent.loading": { id: "Memuat konten...", en: "Loading content..." },
  "adminContent.loadError": { id: "Tidak dapat memuat konten", en: "Unable to load content" },
  "adminContent.savedContent": { id: "Konten Tersimpan", en: "Saved Content" },
  "adminContent.contentSummary": { id: "Ringkasan konten terbaru sekaligus kontrol penghapusan.", en: "Recent content summary with delete controls." },
  "adminContent.untitled": { id: "(Tanpa judul)", en: "(Untitled)" },
  "adminContent.noContent": { id: "Tidak ada konten.", en: "No content." },
  "adminContent.delete": { id: "Hapus", en: "Delete" },
  "adminContent.emptyState": { id: "Belum ada konten yang tersedia untuk ditampilkan.", en: "No content available to display." },
  "adminContent.reload": { id: "Muat Ulang Konten", en: "Reload Content" },
  "adminContent.loadingState": { id: "Memuat...", en: "Loading..." },
  "adminContent.deleteTitle": { id: "Hapus Konten", en: "Delete Content" },
  "adminContent.deleteConfirm": { id: "Hapus konten \"{title}\" secara permanen?", en: "Permanently delete content \"{title}\"?" },
  "adminContent.cancel": { id: "Batal", en: "Cancel" },
  "adminContent.yesDelete": { id: "Ya, Hapus", en: "Yes, Delete" },

  // Admin System
  "adminSystem.title": { id: "Pengaturan Sistem & Log", en: "System Settings & Logs" },
  "adminSystem.description": { id: "Pantau status API dan konfigurasi sistem.", en: "Monitor API status and system configuration." },
  "adminSystem.loading": { id: "Memuat sistem...", en: "Loading system..." },
  "adminSystem.healthError": { id: "Tidak dapat memeriksa status", en: "Unable to check status" },
  "adminSystem.apiStatus": { id: "Status API", en: "API Status" },
  "adminSystem.apiStatusDesc": { id: "Pastikan backend dan Supabase tersedia.", en: "Ensure backend and Supabase are available." },
  "adminSystem.statusLabel": { id: "Status:", en: "Status:" },
  "adminSystem.checking": { id: "Memeriksa...", en: "Checking..." },
  "adminSystem.unavailable": { id: "Tidak tersedia", en: "Unavailable" },
  "adminSystem.totalErrors": { id: "Total Errors", en: "Total Errors" },
  "adminSystem.aiUsageEvents": { id: "AI Usage Events", en: "AI Usage Events" },
  "adminSystem.lastAiQuota": { id: "AI quota terakhir", en: "Last AI Quota" },
  "adminSystem.recentActivity": { id: "Log aktivitas terbaru", en: "Recent Activity Logs" },
  "adminSystem.noActivityLogs": { id: "Tidak ada log aktivitas.", en: "No activity logs." },
  "adminSystem.recentErrors": { id: "Log error terbaru", en: "Recent Error Logs" },
  "adminSystem.noErrorLogs": { id: "Tidak ada log error.", en: "No error logs." },
  "adminSystem.refresh": { id: "Refresh Status", en: "Refresh Status" },
  "adminSystem.loadingState": { id: "Memuat...", en: "Loading..." },

  // Admin Docs
  "adminDocs.title": { id: "Dokumentasi Developer", en: "Developer Documentation" },
  "adminDocs.pinInstruction": { id: "Ini adalah dokumentasi sistem untuk developer. Masukkan kunci untuk melanjutkan.", en: "This is system documentation for developers. Enter the key to continue." },
  "adminDocs.pinHint": { id: "pinnya ini {pin}", en: "the pin is {pin}" },
  "adminDocs.enterPin": { id: "Masukkan PIN untuk mengakses dokumentasi", en: "Enter PIN to access documentation" },
  "adminDocs.pinPlaceholder": { id: "Masukkan PIN", en: "Enter PIN" },
  "adminDocs.wrongPin": { id: "PIN salah, silakan coba lagi.", en: "Wrong PIN, please try again." },
  "adminDocs.openDocs": { id: "Buka Dokumentasi", en: "Open Documentation" },
  "adminDocs.copy": { id: "Copy", en: "Copy" },
  "adminDocs.printSave": { id: "Print / Save PDF", en: "Print / Save PDF" },
  "adminDocs.tabDb": { id: "Database & Triggers", en: "Database & Triggers" },
  "adminDocs.tabFitur": { id: "Arsitektur Fitur", en: "Feature Architecture" },
  "adminDocs.tabApi": { id: "Kontrak API Auth", en: "API Auth Contract" },
  "adminDocs.tabSso": { id: "Dokumentasi SSO", en: "SSO Documentation" },
  "adminDocs.banner": { id: "Dokumentasi teknis sistem Carubra Media Generator. Sistem ini menggunakan Supabase dengan arsitektur modern untuk otentikasi, manajemen media AI, dan transaksi.", en: "Technical documentation for the Carubra Media Generator system. This system uses Supabase with a modern architecture for authentication, AI media management, and transactions." },
  "adminDocs.tableSchemas": { id: "Struktur Tabel Data (Schemas)", en: "Data Table Structures (Schemas)" },
  "adminDocs.tableSchemasDesc": { id: "Daftar seluruh tabel asli yang ada di skema public Supabase.", en: "List of all actual tables in the Supabase public schema." },
  "adminDocs.tableName": { id: "Nama Tabel", en: "Table Name" },
  "adminDocs.tableDesc": { id: "Deskripsi & Fungsi Utama", en: "Description & Main Function" },
  "adminDocs.functionsTriggers": { id: "Database Functions & Triggers Asli", en: "Original Database Functions & Triggers" },
  "adminDocs.functionsDesc": { id: "Fungsi dan Trigger PostgreSQL yang aktif mengatur otomatisasi data di level database.", en: "Active PostgreSQL functions and triggers automating data at the database level." },
  "adminDocs.triggerName": { id: "Nama Trigger / Function", en: "Trigger / Function Name" },
  "adminDocs.triggerEvent": { id: "Event Pemicu", en: "Trigger Event" },
  "adminDocs.triggerResult": { id: "Hasil Otomatisasi", en: "Automation Result" },
  "adminDocs.userFeatureTitle": { id: "A. Fitur Role: USER (Member)", en: "A. User Role Features (Member)" },
  "adminDocs.userFeatureDesc": { id: "Hak akses dan fungsionalitas inti bagi pelanggan (end-user).", en: "Core access rights and functionality for end-users." },
  "adminDocs.adminFeatureTitle": { id: "B. Fitur Role: ADMIN", en: "B. Admin Role Features" },
  "adminDocs.apiEndpoints": { id: "Daftar Endpoint API Terdeteksi", en: "Detected API Endpoints" },
  "adminDocs.apiEndpointsDesc": { id: "Pemetaan rute (/app/api) beserta metodenya.", en: "Route mapping (/app/api) with their methods." },
  "adminDocs.endpoint": { id: "Endpoint Path", en: "Endpoint Path" },
  "adminDocs.method": { id: "Method", en: "Method" },
  "adminDocs.description": { id: "Deskripsi Fungsionalitas", en: "Functionality Description" },
  "adminDocs.responseFormat": { id: "Format Response Aktual (JSON)", en: "Actual Response Format (JSON)" },
  "adminDocs.authArchitecture": { id: "Arsitektur Autentikasi", en: "Authentication Architecture" },
  "adminDocs.authDesc": { id: "Dashboard menggunakan Supabase Auth (email + password) sebagai identity provider.", en: "The dashboard uses Supabase Auth (email + password) as the identity provider." },
  "adminDocs.cookieStrategy": { id: "Cookie Strategy", en: "Cookie Strategy" },
  "adminDocs.cookieStrategyDesc": { id: "Sistem menggunakan Cookie-based session yang aman. Token (access_token dan refresh_token) dikelola melalui mekanisme Next.js Middleware yang mengintersepsi rute privat. Jika token invalid/kedaluwarsa, pengguna secara otomatis dikembalikan ke halaman login.", en: "The system uses secure cookie-based sessions. Tokens (access_token and refresh_token) are managed through Next.js Middleware intercepting private routes. If the token is invalid/expired, the user is automatically redirected to the login page." },
  "adminDocs.aiUsageLogs": { id: "Log pemakaian token API (LLM/AI) untuk keperluan analitik & billing.", en: "API token usage logs (LLM/AI) for analytics & billing purposes." },
  "adminDocs.apiErrorLogs": { id: "Log otomatis untuk menangkap error dari endpoint API eksternal/internal.", en: "Automatic logs for capturing errors from external/internal API endpoints." },
  "adminDocs.contentAnalysis": { id: "Menyimpan data analitik terkait performa konten yang telah diterbitkan.", en: "Stores analytics data related to published content performance." },
  "adminDocs.generatedContents": { id: "Riwayat general dari konten AI (Gambar/Video/Teks) yang diproduksi.", en: "History of AI-generated content (Image/Video/Text) produced." },
  "adminDocs.imageHistory": { id: "Log historis khusus untuk pemrosesan/pembuatan gambar (Image AI).", en: "Historical log for image processing/creation (Image AI)." },
  "adminDocs.images": { id: "Tabel master yang menyimpan detail gambar hasil generate AI.", en: "Master table storing AI-generated image details." },
  "adminDocs.members": { id: "Data khusus member yang berlangganan (detail membership tier).", en: "Subscribed member data (membership tier details)." },
  "adminDocs.membershipPackages": { id: "Katalog data harga dan paket koin yang ditawarkan kepada user.", en: "Catalog of pricing data and coin packages offered to users." },
  "adminDocs.scheduledPosts": { id: "Antrean post/upload yang dijadwalkan ke media sosial terhubung.", en: "Queue of scheduled posts/uploads to connected social media." },
  "adminDocs.socialConnects": { id: "Menyimpan kredensial OAuth (Token) akun media sosial pengguna.", en: "Stores OAuth credentials (Tokens) for user social media accounts." },
  "adminDocs.transactionHistory": { id: "Riwayat log tahapan atau mutasi transaksi pembayaran (status tracking).", en: "Log history of payment transaction stages/mutations (status tracking)." },
  "adminDocs.transactions": { id: "Tabel utama invoice dan status pembayaran pembelian paket koin.", en: "Main table for invoices and payment status of coin package purchases." },
  "adminDocs.userActivityLogs": { id: "Audit trail aktivitas/tindakan pengguna di dalam sistem.", en: "Audit trail of user activities/actions within the system." },
  "adminDocs.userProfileSummary": { id: "Tabel agregasi data profil pengguna (view/summary table).", en: "User profile data aggregation table (view/summary table)." },
  "adminDocs.usersTable": { id: "Tabel sentral pengguna. Menyimpan info role, email, dan jumlah koin.", en: "Central user table. Stores role, email, and coin balance info." },
  "adminDocs.videoHistory": { id: "Log historis khusus untuk pemrosesan/pembuatan video (Video AI).", en: "Historical log for video processing/creation (Video AI)." },
  "adminDocs.videosTable": { id: "Tabel master yang menyimpan detail video hasil generate AI.", en: "Master table storing AI-generated video details." },
  "adminDocs.triggerSetInvoice": { id: "Menggunakan generate_invoice_number() untuk mengisi field nomor invoice secara otomatis sebelum record transaksi tersimpan.", en: "Uses generate_invoice_number() to auto-fill the invoice number field before the transaction record is saved." },
  "adminDocs.triggerSetMembership": { id: "Menggunakan generate_membership_order() untuk men-generate identifier unik keanggotaan saat user baru mendaftar.", en: "Uses generate_membership_order() to generate a unique membership identifier when a new user registers." },
  "adminDocs.triggerUpdateTimestamps": { id: "Secara otomatis memperbarui kolom updated_at ke waktu now() setiap kali ada perubahan data (UPDATE) pada row tersebut.", en: "Automatically updates the updated_at column to now() whenever data changes (UPDATE) on that row." },
  "adminDocs.featureAiGenerator": { id: "AI Video & Image Generator", en: "AI Video & Image Generator" },
  "adminDocs.featureAiGeneratorDesc": { id: "Pengguna memasukkan prompt untuk generate aset. Sistem mengecek dan memotong saldo users.coins, memanggil API (Luma/OpenRouter), lalu menyimpan data ke tabel videos atau images.", en: "Users enter a prompt to generate assets. The system checks and deducts users.coins balance, calls the API (Luma/OpenRouter), then saves data to the videos or images table." },
  "adminDocs.featureSocialConnect": { id: "Social Connect & Auto Upload", en: "Social Connect & Auto Upload" },
  "adminDocs.featureSocialConnectDesc": { id: "Menggunakan OAuth untuk menyimpan kredensial ke social_connects. Postingan dijadwalkan masuk ke scheduled_posts dan dieksekusi oleh background worker ke media sosial.", en: "Uses OAuth to store credentials in social_connects. Scheduled posts are queued in scheduled_posts and executed by a background worker to social media." },
  "adminDocs.featureCoinPurchase": { id: "Pembelian Koin (Xendit)", en: "Coin Purchase (Xendit)" },
  "adminDocs.featureCoinPurchaseDesc": { id: "Pembelian dari membership_packages memicu pembuatan invoice Xendit yang tersimpan di transactions dengan status PENDING. Webhook mengubahnya menjadi PAID.", en: "Purchases from membership_packages trigger Xendit invoice creation stored in transactions with PENDING status. Webhook changes it to PAID." },
  "adminDocs.featureAnalytics": { id: "Content Analytics", en: "Content Analytics" },
  "adminDocs.featureAnalyticsDesc": { id: "Agregasi performa konten (Views, Likes) dari media sosial ditarik dan disajikan di dashboard pengguna dari data content_analysis.", en: "Content performance aggregation (Views, Likes) from social media is fetched and displayed on the user dashboard from content_analysis data." },
  "adminDocs.featureUserManagement": { id: "Manajemen User", en: "User Management" },
  "adminDocs.featureUserManagementDesc": { id: "Admin dapat mengelola akses pengguna, melihat sisa koin, dan melakukan Banned (mengatur kolom is_banned = true).", en: "Admins can manage user access, view remaining coins, and Ban users (setting is_banned = true)." },
  "adminDocs.featurePricing": { id: "Manajemen Harga Paket", en: "Package Price Management" },
  "adminDocs.featurePricingDesc": { id: "Admin mengatur penawaran harga di tabel membership_packages secara dinamis tanpa mengubah kode frontend.", en: "Admins dynamically manage pricing offers in the membership_packages table without changing frontend code." },
  "adminDocs.featureMonitoring": { id: "Monitoring & System Logs", en: "Monitoring & System Logs" },
  "adminDocs.featureMonitoringDesc": { id: "Akses penuh membaca api_error_logs untuk debugging dan ai_usage_logs untuk memantau beban operasional/biaya token LLM secara real-time.", en: "Full read access to api_error_logs for debugging and ai_usage_logs for monitoring operational load/LLM token costs in real-time." },
  "adminDocs.sectionAuth": { id: "Otentikasi & Profil", en: "Authentication & Profile" },
  "adminDocs.apiLogin": { id: "Validasi kredensial & set Session Cookie.", en: "Validate credentials & set Session Cookie." },
  "adminDocs.apiRegister": { id: "Pendaftaran user baru ke DB.", en: "Register new user to DB." },
  "adminDocs.apiProfile": { id: "Ambil/update profil aktif.", en: "Get/update active profile." },
  "adminDocs.sectionAiGenerator": { id: "Generator AI", en: "AI Generator" },
  "adminDocs.apiVideoGenerate": { id: "Generate video AI dari prompt (Potong Koin).", en: "Generate AI video from prompt (Deduct Coins)." },
  "adminDocs.apiImageGenerate": { id: "Generate gambar AI dari prompt (Potong Koin).", en: "Generate AI image from prompt (Deduct Coins)." },
  "adminDocs.sectionPayment": { id: "Top-up & Payment", en: "Top-up & Payment" },
  "adminDocs.apiCreateInvoice": { id: "Buat request invoice Xendit.", en: "Create Xendit invoice request." },
  "adminDocs.apiWebhook": { id: "Callback dari Xendit saat lunas.", en: "Callback from Xendit when paid." },
  "adminDocs.responseFormatDesc": { id: "Struktur balikan (response) asli berdasarkan file kode di server.", en: "Actual response structure based on server code files." },
  "adminDocs.codeRegister": { id: "1. Registrasi Berhasil (/api/auth/register)", en: "1. Registration Success (/api/auth/register)" },
  "adminDocs.codeVideoGenerate": { id: "2. Request Generate Video AI (/api/video-ai/generate)", en: "2. Video AI Generate Request (/api/video-ai/generate)" },
  "adminDocs.codeCreateInvoice": { id: "3. Buat Tagihan Pembayaran Xendit (/api/payments/create-invoice)", en: "3. Create Xendit Payment Invoice (/api/payments/create-invoice)" },
  "adminDocs.codeError": { id: "4. Response Jika Terjadi Error (Umum)", en: "4. Error Response (General)" },

  // Video AI
  "videoAi.title": { id: "Generator Video AI", en: "AI Video Generator" },
  "videoAi.script": { id: "Script", en: "Script" },
  "videoAi.scriptPlaceholder": { id: "Masukkan script video Anda...", en: "Enter your video script..." },
  "videoAi.resolution": { id: "Resolusi", en: "Resolution" },
  "videoAi.resolution480p": { id: "480p (Standar)", en: "480p (Standard)" },
  "videoAi.resolution720p": { id: "720p (HD)", en: "720p (HD)" },
  "videoAi.resolution1080p": { id: "1080p (Full HD)", en: "1080p (Full HD)" },
  "videoAi.resolution2k": { id: "2K", en: "2K" },
  "videoAi.ratio": { id: "Rasio Video", en: "Video Ratio" },
  "videoAi.ratio2-3": { id: "2:3 (Potrait)", en: "2:3 (Portrait)" },
  "videoAi.ratio3-2": { id: "3:2 (Landscape)", en: "3:2 (Landscape)" },
  "videoAi.ratio1-1": { id: "1:1 (Square)", en: "1:1 (Square)" },
  "videoAi.ratio16-9": { id: "16:9 (Widescreen)", en: "16:9 (Widescreen)" },
  "videoAi.ratio9-16": { id: "9:16 (Vertical)", en: "9:16 (Vertical)" },
  "videoAi.ratio4-3": { id: "4:3 (Standard)", en: "4:3 (Standard)" },
  "videoAi.ratio3-4": { id: "3:4 (Portrait)", en: "3:4 (Portrait)" },
  "videoAi.model": { id: "Model", en: "Model" },
  "videoAi.textToVideo": { id: "Text to Video", en: "Text to Video" },
  "videoAi.imageToVideo": { id: "Image to Video", en: "Image to Video" },
  "videoAi.duration": { id: "Durasi Video", en: "Video Duration" },
  "videoAi.durationLabel": { id: "Durasi (detik)", en: "Duration (seconds)" },
  "videoAi.durationPlaceholder": { id: "30", en: "30" },
  "videoAi.durationMax": { id: "Maksimal 60 detik", en: "Maximum 60 seconds" },
  "videoAi.coin": { id: "Biaya Koin", en: "Coin Cost" },
  "videoAi.coinCost": { id: "Biaya generate", en: "Generation cost" },
  "videoAi.coin480p": { id: "2 koin (480p)", en: "2 coins (480p)" },
  "videoAi.coin720p": { id: "3 koin (720p HD)", en: "3 coins (720p HD)" },
  "videoAi.coinBalance": { id: "Saldo Koin Tersisa", en: "Remaining Coin Balance" },
  "videoAi.insufficientBalance": { id: "Saldo koin tidak cukup.", en: "Insufficient coin balance." },
  "videoAi.generate": { id: "Generate Video", en: "Generate Video" },
  "videoAi.generating": { id: "Sedang membuat video...", en: "Generating video..." },
  "videoAi.generatingState": { id: "Sedang Generate...", en: "Generating..." },
  "videoAi.selectOptions": { id: "Harap pilih dan isi semua opsi sebelum generate", en: "Please select and fill all options before generating" },
  "videoAi.caption": { id: "Caption", en: "Caption" },
  "videoAi.shareToSocial": { id: "Bagikan ke Sosial Media", en: "Share to Social Media" },
  "videoAi.history": { id: "Riwayat Generate Video", en: "Video Generation History" },
  "videoAi.gallery": { id: "Galeri Video", en: "Video Gallery" },
  "videoAi.detail": { id: "Detail", en: "Detail" },
  "videoAi.edit": { id: "Edit", en: "Edit" },
  "videoAi.send": { id: "Kirim", en: "Send" },
  "videoAi.delete": { id: "Hapus", en: "Delete" },
  "videoAi.completed": { id: "Selesai", en: "Completed" },
  "videoAi.failed": { id: "Gagal", en: "Failed" },
  "videoAi.processing": { id: "Proses...", en: "Processing..." },
  "videoAi.completedIn": { id: "Selesai dalam", en: "Completed in" },
  "videoAi.noVideosGenerated": { id: "Belum ada video yang dibuat", en: "No videos generated yet" },
  "videoAi.videoTitle": { id: "Judul Video", en: "Video Title" },
  "videoAi.videoTitlePlaceholder": { id: "Masukkan judul video...", en: "Enter video title..." },
  "videoAi.scriptDescription": { id: "Script / Deskripsi", en: "Script / Description" },
  "videoAi.scriptDescriptionPlaceholder": { id: "Deskripsikan video yang ingin kamu buat...", en: "Describe the video you want to create..." },
  "videoAi.sourceImage": { id: "Gambar Sumber", en: "Source Image" },
  "videoAi.clickToUpload": { id: "Klik untuk upload gambar", en: "Click to upload image" },
  "videoAi.resultTitle": { id: "Hasil Generate", en: "Generation Result" },
  "videoAi.waitingResult": { id: "Hasil video akan tampil di sini", en: "Video result will appear here" },
  "videoAi.generatingVideo": { id: "Membuat video...", en: "Creating video..." },
  "videoAi.mayTakeMinutes": { id: "Ini mungkin memerlukan beberapa menit", en: "This may take a few minutes" },
  "videoAi.generationFailed": { id: "Generate video gagal", en: "Video generation failed" },
  "videoAi.tryDifferentPrompt": { id: "Coba lagi dengan prompt berbeda", en: "Try again with a different prompt" },
  "videoAi.videoCreated": { id: "Video berhasil dibuat", en: "Video created successfully" },
  "videoAi.previewUnavailable": { id: "Preview tidak tersedia", en: "Preview unavailable" },
  "videoAi.videoFailed": { id: "Video gagal dibuat", en: "Video creation failed" },
  "videoAi.modalModel": { id: "Model", en: "Model" },
  "videoAi.modalResolution": { id: "Resolusi", en: "Resolution" },
  "videoAi.modalDuration": { id: "Durasi Video", en: "Video Duration" },
  "videoAi.modalDurationValue": { id: "{duration} detik", en: "{duration} seconds" },
  "videoAi.modalGenerateTime": { id: "Waktu Generate", en: "Generation Time" },
  "videoAi.modalCost": { id: "Biaya", en: "Cost" },
  "videoAi.modalCreated": { id: "Dibuat", en: "Created" },
  "videoAi.seconds": { id: "{s} detik", en: "{s} seconds" },
  "videoAi.minutes": { id: "{m} menit", en: "{m} minutes" },
  "videoAi.scriptLabel": { id: "SCRIPT / DESKRIPSI", en: "SCRIPT / DESCRIPTION" },
  "videoAi.captionLabel": { id: "CAPTION", en: "CAPTION" },
  "videoAi.copyCaption": { id: "Copy", en: "Copy" },
  "videoAi.preparingCaption": { id: "Menyiapkan caption...", en: "Preparing caption..." },
  "videoAi.noCaption": { id: "Tidak ada caption.", en: "No caption." },
  "videoAi.shareTo": { id: "BAGIKAN KE", en: "SHARE TO" },
  "videoAi.deleteVideo": { id: "Hapus Video", en: "Delete Video" },
  "videoAi.videoTitleLabel": { id: "JUDUL VIDEO", en: "VIDEO TITLE" },
  "videoAi.editTitlePlaceholder": { id: "Edit judul video...", en: "Edit video title..." },
  "videoAi.editScriptPlaceholder": { id: "Edit script untuk generate ulang video...", en: "Edit script to regenerate video..." },
  "videoAi.regenVideo": { id: "Generate Ulang Video", en: "Regenerate Video" },
  "videoAi.editCaptionPlaceholder": { id: "Edit caption atau generate ulang...", en: "Edit caption or regenerate..." },
  "videoAi.regenCaption": { id: "Generate Ulang Caption", en: "Regenerate Caption" },
  "videoAi.saving": { id: "Menyimpan...", en: "Saving..." },
  "videoAi.saveChanges": { id: "Simpan Perubahan", en: "Save Changes" },
  "videoAi.shared": { id: "Dibagikan!", en: "Shared!" },
  "videoAi.secondsAbbr": { id: "dtk", en: "s" },
  "videoAi.captionGenerating": { id: "Membuat Caption...", en: "Generating Caption..." },
  "videoAi.generatingVideoLong": { id: "Generating...", en: "Generating..." },

  // Image AI
  "imageAi.title": { id: "Generator Gambar AI", en: "AI Image Generator" },
  "imageAi.header": { id: "Image AI", en: "Image AI" },
  "imageAi.headerDesc": { id: "Buat gambar dengan AI dari deskripsi teks", en: "Create images with AI from text descriptions" },
  "imageAi.prompt": { id: "Deskripsi Gambar", en: "Image Description" },
  "imageAi.promptPlaceholder": { id: "Deskripsikan gambar yang ingin kamu buat...", en: "Describe the image you want to create..." },
  "imageAi.generate": { id: "Generate Gambar", en: "Generate Image" },
  "imageAi.generating": { id: "Sedang membuat gambar...", en: "Generating image..." },
  "imageAi.generateForm": { id: "Generate Gambar", en: "Generate Image" },
  "imageAi.generatingState": { id: "Sedang Generate...", en: "Generating..." },
  "imageAi.model": { id: "Model", en: "Model" },
  "imageAi.textToImage": { id: "Text to Image", en: "Text to Image" },
  "imageAi.imageToImage": { id: "Image to Image", en: "Image to Image" },
  "imageAi.sourceImage": { id: "Gambar Sumber", en: "Source Image" },
  "imageAi.clickToUpload": { id: "Klik untuk upload gambar", en: "Click to upload image" },
  "imageAi.tipLabel": { id: "Tips:", en: "Tip:" },
  "imageAi.tipText": { id: "Jelaskan dengan spesifik apa yang ingin diubah dan apa yang ingin dipertahankan", en: "Describe specifically what you want to change and what to keep" },
  "imageAi.aspectRatio": { id: "Rasio Gambar", en: "Aspect Ratio" },
  "imageAi.resolution": { id: "Resolusi Output", en: "Output Resolution" },
  "imageAi.outputSize": { id: "Output: {w}x{h}px", en: "Output: {w}x{h}px" },
  "imageAi.coinCost": { id: "Biaya generate", en: "Generation cost" },
  "imageAi.insufficientBalance": { id: "Saldo koin tidak cukup.", en: "Insufficient coin balance." },
  "imageAi.resultTitle": { id: "Hasil Generate", en: "Generation Result" },
  "imageAi.waitingResult": { id: "Hasil gambar akan tampil di sini", en: "Image result will appear here" },
  "imageAi.generatingImage": { id: "Membuat gambar...", en: "Creating image..." },
  "imageAi.mayTakeSeconds": { id: "Ini mungkin memerlukan beberapa detik", en: "This may take a few seconds" },
  "imageAi.download": { id: "Download", en: "Download" },
  "imageAi.copyUrl": { id: "Copy URL", en: "Copy URL" },
  "imageAi.reset": { id: "Reset", en: "Reset" },
  "imageAi.shareToSocial": { id: "Bagikan ke Sosial Media", en: "Share to Social Media" },
  "imageAi.noAccounts": { id: "Belum ada akun sosmed yang terhubung.", en: "No social media accounts connected." },
  "imageAi.generateCaption": { id: "Generate Caption", en: "Generate Caption" },
  "imageAi.captionPlaceholder": { id: "Minta caption sesuai gambar...", en: "Request a caption for this image..." },
  "imageAi.generatingCaption": { id: "Membuat caption...", en: "Generating caption..." },
  "imageAi.captionFailed": { id: "Gagal membuat caption.", en: "Failed to generate caption." },
  "imageAi.historyTab": { id: "History Generate", en: "Generation History" },
  "imageAi.galleryTab": { id: "Galeri Gambar", en: "Image Gallery" },
  "imageAi.noHistory": { id: "Belum ada riwayat generate", en: "No generation history" },
  "imageAi.noGallery": { id: "Belum ada gambar di galeri", en: "No images in gallery" },
  "imageAi.captionPrefix": { id: "Caption:", en: "Caption:" },
  "imageAi.modalModel": { id: "Model", en: "Model" },
  "imageAi.modalRatio": { id: "Rasio", en: "Ratio" },
  "imageAi.modalResolution": { id: "Resolusi", en: "Resolution" },
  "imageAi.modalDuration": { id: "Durasi", en: "Duration" },
  "imageAi.captionLabel": { id: "CAPTION", en: "CAPTION" },
  "imageAi.copyCaption": { id: "Copy", en: "Copy" },
  "imageAi.noCaption": { id: "Tidak ada caption.", en: "No caption." },
  "imageAi.editPromptLabel": { id: "PROMPT GAMBAR", en: "IMAGE PROMPT" },
  "imageAi.editPromptPlaceholder": { id: "Edit prompt untuk generate ulang gambar...", en: "Edit prompt to regenerate image..." },
  "imageAi.regenImage": { id: "Generate Ulang Gambar", en: "Regenerate Image" },
  "imageAi.editCaptionPlaceholder": { id: "Edit caption...", en: "Edit caption..." },
  "imageAi.regenCaption": { id: "Generate Ulang Caption", en: "Regenerate Caption" },
  "imageAi.saveChanges": { id: "Simpan Perubahan", en: "Save Changes" },
  "imageAi.saving": { id: "Menyimpan...", en: "Saving..." },
  "imageAi.shared": { id: "Dibagikan!", en: "Shared!" },
  "imageAi.deleteImage": { id: "Hapus Gambar", en: "Delete Image" },
  "imageAi.generatingLong": { id: "Generating...", en: "Generating..." },
  "imageAi.captionGenerating": { id: "Membuat Caption...", en: "Generating Caption..." },

  // Auto Upload
  "autoUpload.title": { id: "Upload Otomatis", en: "Auto Upload" },
  "autoUpload.description": { id: "Jadwalkan dan publikasikan konten ke semua platform dari satu tempat", en: "Schedule and publish content to all platforms from one place" },
  "autoUpload.fetchError": { id: "Terjadi kesalahan pada server", en: "An error occurred on the server" },
  "autoUpload.retry": { id: "Coba lagi", en: "Retry" },
  "autoUpload.connections": { id: "Koneksi Media Sosial", en: "Social Media Connections" },
  "autoUpload.connected": { id: "Terhubung", en: "Connected" },
  "autoUpload.connect": { id: "Hubungkan", en: "Connect" },
  "autoUpload.schedulePost": { id: "Jadwalkan Postingan", en: "Schedule Post" },
  "autoUpload.date": { id: "Tanggal", en: "Date" },
  "autoUpload.time": { id: "Waktu", en: "Time" },
  "autoUpload.contentSource": { id: "Pilih Sumber Konten", en: "Select Content Source" },
  "autoUpload.upload": { id: "Upload", en: "Upload" },
  "autoUpload.generated": { id: "Generated", en: "Generated" },
  "autoUpload.clickToUpload": { id: "Klik untuk upload gambar atau video", en: "Click to upload image or video" },
  "autoUpload.uploadLimit": { id: "JPG, PNG, MP4, MOV — maks 100MB", en: "JPG, PNG, MP4, MOV — max 100MB" },
  "autoUpload.remove": { id: "Hapus", en: "Remove" },
  "autoUpload.loadingGenerated": { id: "Memuat generated contents...", en: "Loading generated contents..." },
  "autoUpload.noGenerated": { id: "Belum ada konten generated.", en: "No generated content yet." },
  "autoUpload.captionLabel": { id: "Caption / Teks Postingan", en: "Caption / Post Text" },
  "autoUpload.captionPlaceholder": { id: "Tulis caption postinganmu... atau terisi otomatis dari hasil generate AI.", en: "Write your post caption... or it will auto-fill from AI generation." },
  "autoUpload.captionFailed": { id: "Gagal membuat caption. Silakan tulis manual.", en: "Failed to generate caption. Please write manually." },
  "autoUpload.selectPlatform": { id: "Pilih Platform", en: "Select Platform" },
  "autoUpload.selectAll": { id: "Pilih Semua", en: "Select All" },
  "autoUpload.deselectAll": { id: "Batal Pilih Semua", en: "Deselect All" },
  "autoUpload.loadingPlatforms": { id: "Memuat platform...", en: "Loading platforms..." },
  "autoUpload.noConnectedPlatforms": { id: "Belum ada akun terhubung. Hubungkan platform di atas terlebih dahulu.", en: "No accounts connected. Connect platforms above first." },
  "autoUpload.postType": { id: "Tipe Postingan per Platform", en: "Post Type per Platform" },
  "autoUpload.selectType": { id: "Pilih tipe", en: "Select type" },
  "autoUpload.schedule": { id: "Jadwalkan", en: "Schedule" },
  "autoUpload.saveDraft": { id: "Simpan Draft", en: "Save Draft" },
  "autoUpload.cancel": { id: "Batal", en: "Cancel" },
  "autoUpload.history": { id: "History Postingan Terjadwal", en: "Scheduled Post History" },
  "autoUpload.postCount": { id: "{count} postingan", en: "{count} posts" },
  "autoUpload.runSchedule": { id: "Jalankan Jadwal", en: "Run Schedule" },
  "autoUpload.loadingPosts": { id: "Memuat postingan...", en: "Loading posts..." },
  "autoUpload.noPosts": { id: "Belum ada postingan terjadwal", en: "No scheduled posts" },
  "autoUpload.withoutCaption": { id: "Postingan tanpa caption", en: "Post without caption" },
  "autoUpload.instagramInstructions": { id: "Sebelum Menghubungkan Instagram", en: "Before Connecting Instagram" },
  "autoUpload.igRequirements": { id: "Pastikan syarat berikut terpenuhi", en: "Make sure the following requirements are met" },
  "autoUpload.igApiTitle": { id: "Persyaratan Instagram Business API:", en: "Instagram Business API Requirements:" },
  "autoUpload.igReq1": { id: "Akun Instagram harus bertipe Bisnis atau Kreator", en: "Instagram account must be Business or Creator type" },
  "autoUpload.igReq2": { id: "Akun Instagram harus sudah dihubungkan ke Facebook Page", en: "Instagram account must be connected to a Facebook Page" },
  "autoUpload.igReq3": { id: "Kamu harus menjadi Admin dari Facebook Page tersebut", en: "You must be an Admin of that Facebook Page" },
  "autoUpload.noFbPage": { id: "Belum punya Facebook Page?", en: "Don't have a Facebook Page?" },
  "autoUpload.createFbPage": { id: "Buat Facebook Page gratis →", en: "Create a free Facebook Page →" },
  "autoUpload.switchToBusiness": { id: "Cara ubah akun ke Bisnis/Kreator:", en: "How to switch to Business/Creator account:" },
  "autoUpload.switchInstructions": { id: "Instagram → Pengaturan → Akun → Beralih ke Akun Profesional", en: "Instagram → Settings → Account → Switch to Professional Account" },
  "autoUpload.connectInstagram": { id: "Lanjut ke Instagram", en: "Proceed to Instagram" },
  "autoUpload.connecting": { id: "Menghubungkan...", en: "Connecting..." },
  "autoUpload.connectAccount": { id: "Hubungkan Akun", en: "Connect Account" },
  "autoUpload.accountDetail": { id: "Detail akun yang terhubung", en: "Connected account details" },
  "autoUpload.username": { id: "Username", en: "Username" },
  "autoUpload.connectedSince": { id: "Terhubung sejak", en: "Connected since" },
  "autoUpload.disconnectConfirm": { id: "Yakin ingin memutus sambungan?", en: "Are you sure you want to disconnect?" },
  "autoUpload.yesDisconnect": { id: "Ya, Putuskan", en: "Yes, Disconnect" },
  "autoUpload.disconnect": { id: "Putus Sambungan", en: "Disconnect" },
  "autoUpload.secureConnection": { id: "Koneksi aman — data tersimpan di database & hanya bisa diakses oleh kamu.", en: "Secure connection — data is stored in the database and only accessible by you." },
  "autoUpload.connectError": { id: "Gagal memulai koneksi {platform}: {message}", en: "Failed to start {platform} connection: {message}" },
  "autoUpload.usernameRequired": { id: "Username tidak boleh kosong.", en: "Username cannot be empty." },
  "autoUpload.disconnectError": { id: "Gagal memutus: {message}", en: "Failed to disconnect: {message}" },
  "autoUpload.deleteError": { id: "Gagal hapus: {message}", en: "Failed to delete: {message}" },
  "autoUpload.dateTimeRequired": { id: "Tanggal dan waktu wajib diisi.", en: "Date and time are required." },
  "autoUpload.selectPlatformError": { id: "Pilih minimal satu platform.", en: "Select at least one platform." },
  "autoUpload.selectMediaError": { id: "Pilih media dari upload atau generated content.", en: "Select media from upload or generated content." },
  "autoUpload.selectPostTypeError": { id: "Pilih tipe postingan untuk {platform}", en: "Select post type for {platform}" },
  "autoUpload.runResultSuccess": { id: "Diproses: {posted} berhasil, {failed} gagal.", en: "Processed: {posted} succeeded, {failed} failed." },
  "autoUpload.runFailed": { id: "Gagal menjalankan jadwal: {message}", en: "Failed to run schedule: {message}" },
  "autoUpload.runResultTitle": { id: "Hasil Eksekusi", en: "Execution Result" },
  "autoUpload.errorTitle": { id: "Error", en: "Error" },
  "autoUpload.comingSoonTitle": { id: "Segera Hadir", en: "Coming Soon" },
  "autoUpload.comingSoonDesc": { id: "Koneksi untuk {platform} akan segera tersedia.", en: "Connection for {platform} will be available soon." },
  "autoUpload.scheduled": { id: "Terjadwal", en: "Scheduled" },
  "autoUpload.posted": { id: "Selesai", en: "Posted" },
  "autoUpload.failed": { id: "Gagal", en: "Failed" },
  "autoUpload.partial": { id: "Sebagian", en: "Partial" },
  "autoUpload.draft": { id: "Draft", en: "Draft" },
  "autoUpload.fileSize": { id: "{size} KB", en: "{size} KB" },
  "autoUpload.instagramConnectLabel": { id: "Masuk dengan Instagram", en: "Sign in with Instagram" },
  "autoUpload.instagramConnectHint": { id: "Mulai koneksi Instagram Business atau Creator melalui OAuth. Pastikan akun sudah terhubung ke Facebook Page.", en: "Start Instagram Business or Creator connection via OAuth. Make sure your account is connected to a Facebook Page." },
  "autoUpload.instagramUsernameLabel": { id: "Username Instagram", en: "Instagram Username" },
  "autoUpload.instagramUsernamePlaceholder": { id: "@namakamu", en: "@yourname" },
  "autoUpload.facebookConnectLabel": { id: "Masuk dengan Facebook", en: "Sign in with Facebook" },
  "autoUpload.facebookConnectHint": { id: "Mulai OAuth untuk menghubungkan Facebook Page kamu. Pastikan kamu adalah Admin halaman tersebut.", en: "Start OAuth to connect your Facebook Page. Make sure you are an Admin of that page." },
  "autoUpload.facebookUsernameLabel": { id: "Nama Facebook Page", en: "Facebook Page Name" },
  "autoUpload.facebookUsernamePlaceholder": { id: "Nama Page / @username", en: "Page Name / @username" },
  "autoUpload.tiktokConnectLabel": { id: "Masuk dengan TikTok", en: "Sign in with TikTok" },
  "autoUpload.tiktokConnectHint": { id: "Hubungkan akun TikTok melalui OAuth untuk memeriksa apakah koneksi dapat dibuat.", en: "Connect TikTok account via OAuth to check if connection can be established." },
  "autoUpload.tiktokUsernameLabel": { id: "Username TikTok", en: "TikTok Username" },
  "autoUpload.tiktokUsernamePlaceholder": { id: "@namakamu", en: "@yourname" },
  "autoUpload.youtubeConnectLabel": { id: "Masuk dengan Google", en: "Sign in with Google" },
  "autoUpload.youtubeConnectHint": { id: "Hubungkan channel YouTube kamu melalui akun Google untuk menjadwalkan upload video.", en: "Connect your YouTube channel via Google account to schedule video uploads." },
  "autoUpload.youtubeUsernameLabel": { id: "Nama Channel YouTube", en: "YouTube Channel Name" },
  "autoUpload.youtubeUsernamePlaceholder": { id: "Nama Channel", en: "Channel Name" },
  "autoUpload.twitterConnectLabel": { id: "Masuk dengan X", en: "Sign in with X" },
  "autoUpload.twitterConnectHint": { id: "Gunakan OAuth untuk menghubungkan akun X/Twitter dan mengaktifkan penjadwalan tweet.", en: "Use OAuth to connect X/Twitter account and enable tweet scheduling." },
  "autoUpload.twitterUsernameLabel": { id: "Username X", en: "X Username" },
  "autoUpload.twitterUsernamePlaceholder": { id: "@namakamu", en: "@yourname" },
  "autoUpload.threadsConnectLabel": { id: "Masuk dengan Threads", en: "Sign in with Threads" },
  "autoUpload.threadsConnectHint": { id: "Gunakan OAuth untuk menghubungkan akun Threads dan mengaktifkan penjadwalan post.", en: "Use OAuth to connect Threads account and enable post scheduling." },
  "autoUpload.threadsUsernameLabel": { id: "Username Threads", en: "Threads Username" },
  "autoUpload.threadsUsernamePlaceholder": { id: "@namakamu", en: "@yourname" },
  "autoUpload.serverError": { id: "Terjadi kesalahan pada server", en: "An error occurred on the server" },

  // Content Analytics
  "analytics.title": { id: "Content Strategy AI", en: "Content Strategy AI" },
  "analytics.poweredBy": { id: "Powered by AI", en: "Powered by AI" },
  "analytics.promptPlaceholder": { id: "Deskripsikan konten yang ingin kamu buat... contoh: 'launching produk skincare baru buat Gen Z, mau viral di TikTok, budget minim tapi kesan premium'", en: "Describe the content you want to create... example: 'launching a new skincare product for Gen Z, want to go viral on TikTok, minimal budget but premium feel'" },
  "analytics.generateStrategy": { id: "Generate strategi →", en: "Generate strategy →" },
  "analytics.generating": { id: "Generating...", en: "Generating..." },
  "analytics.generateError": { id: "Deskripsikan konten yang ingin kamu buat", en: "Describe the content you want to create" },
  "analytics.promptRequired": { id: "Deskripsikan konten yang ingin kamu buat", en: "Describe the content you want to create" },
  "analytics.aiThinking": { id: "AI sedang menyusun strategi konten kamu...", en: "AI is crafting your content strategy..." },
  "analytics.emptyTitle": { id: "Belum ada strategi", en: "No strategy yet" },
  "analytics.emptyDesc": { id: "Tulis deskripsi konten yang kamu inginkan, pilih platform dan audience, lalu biarkan AI menyusun strategi lengkap untukmu.", en: "Write a description of the content you want, choose a platform and audience, then let AI create a complete strategy for you." },
  "analytics.viralScore": { id: "Viral score", en: "Viral score" },
  "analytics.hookLabel": { id: "Hook 3 detik pertama", en: "First 3-second hook" },
  "analytics.contentFlow": { id: "Alur konten", en: "Content flow" },
  "analytics.estimatedViews": { id: "Est. views", en: "Est. views" },
  "analytics.estReach": { id: "estimasi jangkauan", en: "estimated reach" },
  "analytics.engagementRate": { id: "Engagement rate", en: "Engagement rate" },
  "analytics.aboveAverage": { id: "Di atas rata-rata", en: "Above average" },
  "analytics.industryAverage": { id: "Rata-rata industri", en: "Industry average" },
  "analytics.bestPostTime": { id: "Best post time", en: "Best post time" },
  "analytics.captionScore": { id: "Caption score", en: "Caption score" },
  "analytics.excellent": { id: "Sangat baik", en: "Excellent" },
  "analytics.fair": { id: "Cukup baik", en: "Fair" },
  "analytics.needsImprovement": { id: "Perlu perbaikan", en: "Needs improvement" },
  "analytics.captionScoreValue": { id: "{score}/100", en: "{score}/100" },
  "analytics.caption": { id: "Caption", en: "Caption" },
  "analytics.copied": { id: "✓ Copied", en: "✓ Copied" },
  "analytics.copy": { id: "Copy", en: "Copy" },
  "analytics.hashtag": { id: "Hashtag", en: "Hashtag" },
  "analytics.contentFormats": { id: "Format konten", en: "Content formats" },
  "analytics.engagementTrend": { id: "Proyeksi engagement trend — 30 hari", en: "Engagement trend projection — 30 days" },
  "analytics.contentFlowDiagram": { id: "Diagram alur konten", en: "Content flow diagram" },
  "analytics.sentimentAnalysis": { id: "Analisis sentimen", en: "Sentiment analysis" },
  "analytics.audienceMatch": { id: "Audience match", en: "Audience match" },
  "analytics.estReachPerPlatform": { id: "Est. reach per platform", en: "Est. reach per platform" },
  "analytics.positive": { id: "Positif {pct}%", en: "Positive {pct}%" },
  "analytics.neutral": { id: "Netral {pct}%", en: "Neutral {pct}%" },
  "analytics.negative": { id: "Negatif {pct}%", en: "Negative {pct}%" },
  "analytics.aiRecommendations": { id: "Rekomendasi strategi AI", en: "AI Strategy Recommendations" },
  "analytics.priorityHigh": { id: "Penting", en: "High Priority" },
  "analytics.priorityMedium": { id: "Disarankan", en: "Recommended" },
  "analytics.priorityLow": { id: "Opsional", en: "Optional" },
  "analytics.ctaVariations": { id: "Variasi Call to Action", en: "Call to Action Variations" },
  "analytics.competitorInsight": { id: "Insight kompetitor", en: "Competitor Insight" },
  "analytics.history": { id: "Riwayat strategi", en: "Strategy history" },
  "analytics.loadingHistory": { id: "Memuat riwayat...", en: "Loading history..." },
  "analytics.noHistory": { id: "Belum ada riwayat strategi.", en: "No strategy history yet." },
  "analytics.completed": { id: "Selesai", en: "Completed" },
  "analytics.processing": { id: "Diproses...", en: "Processing..." },
  "analytics.failed": { id: "Gagal", en: "Failed" },
  "analytics.detailTitle": { id: "Detail Strategi Konten", en: "Content Strategy Details" },
  "analytics.detailDesc": { id: "Hasil generasi AI untuk prompt: {prompt}", en: "AI generation result for prompt: {prompt}" },
  "analytics.timeAgoDays": { id: "{d} hari lalu", en: "{d} days ago" },
  "analytics.timeAgoHours": { id: "{h} jam lalu", en: "{h} hours ago" },
  "analytics.timeAgoJustNow": { id: "Baru saja", en: "Just now" },

  // WhatsApp Setup
  "whatsapp.notConfiguredTitle": { id: "GoWA belum dikonfigurasi", en: "GoWA Not Configured" },
  "whatsapp.notConfiguredDesc": { id: "Silakan atur environment variable GOWA_BASE_URL di developer atau server.", en: "Please set the GOWA_BASE_URL environment variable in the developer settings or server." },
  "whatsapp.setupTitle": { id: "WhatsApp Setup", en: "WhatsApp Setup" },
  "whatsapp.heading": { id: "Hubungkan WhatsApp lewat QR GoWA", en: "Connect WhatsApp via GoWA QR" },
  "whatsapp.description": { id: "Buka GoWA dan scan QR untuk menghubungkan akun WhatsApp kamu. Setelah berhasil, kembali ke dashboard untuk menyimpan nomor.", en: "Open GoWA and scan the QR to connect your WhatsApp account. Once successful, return to the dashboard to save the number." },
  "whatsapp.urlLabel": { id: "URL Setup GoWA", en: "GoWA Setup URL" },
  "whatsapp.urlDesc": { id: "Buka URL berikut di browser untuk melihat QR code GoWA.", en: "Open the following URL in your browser to see the GoWA QR code." },
  "whatsapp.refresh": { id: "Refresh", en: "Refresh" },
  "whatsapp.url": { id: "URL", en: "URL" },
  "whatsapp.copyUrl": { id: "Salin URL", en: "Copy URL" },
  "whatsapp.openGowa": { id: "Buka GoWA", en: "Open GoWA" },
  "whatsapp.openGowaHint": { id: "Klik tombol Buka GoWA di atas. Setelah halaman GoWA terbuka dan menampilkan QR Code aslinya, scan QR tersebut menggunakan aplikasi WhatsApp di HP kamu.", en: "Click the Open GoWA button above. Once the GoWA page opens and displays the actual QR Code, scan it using the WhatsApp app on your phone." },
  "whatsapp.phoneNumber": { id: "Nomor WhatsApp", en: "WhatsApp Number" },
  "whatsapp.required": { id: "Required", en: "Required" },
  "whatsapp.phoneHint": { id: "Masukkan nomor WA yang sudah terhubung lewat GoWA. Ini diperlukan agar Carubra bisa menjadwalkan pesan ke nomor tersebut.", en: "Enter the WhatsApp number connected via GoWA. This is needed for Carubra to schedule messages to that number." },
  "whatsapp.phoneInputLabel": { id: "Nomor WhatsApp", en: "WhatsApp Number" },
  "whatsapp.phonePlaceholder": { id: "+62 812 3456 7890", en: "+62 812 3456 7890" },
  "whatsapp.savePhone": { id: "Simpan nomor WA", en: "Save WA number" },
  "whatsapp.saving": { id: "Menyimpan...", en: "Saving..." },
  "whatsapp.backToDashboard": { id: "Kembali ke Dashboard", en: "Back to Dashboard" },
  "whatsapp.quickSteps": { id: "Langkah cepat", en: "Quick steps" },
  "whatsapp.step1": { id: "Buka link GoWA dan scan QR.", en: "Open GoWA link and scan QR." },
  "whatsapp.step2": { id: "Tunggu GoWA menghubungkan akun WhatsApp kamu.", en: "Wait for GoWA to connect your WhatsApp account." },
  "whatsapp.step3": { id: "Kembali ke dashboard dan simpan nomor WA.", en: "Return to the dashboard and save the WA number." },
  "whatsapp.step4": { id: "Gunakan nomor tersebut untuk menjadwalkan pesan WA.", en: "Use that number to schedule WA messages." },
  "whatsapp.importantNotes": { id: "Catatan penting", en: "Important notes" },
  "whatsapp.note1": { id: "GoWA client ID dikelola oleh developer. Kamu hanya perlu scan QR dan memasukkan nomor WA.", en: "GoWA client ID is managed by the developer. You only need to scan the QR and enter the WA number." },
  "whatsapp.note2": { id: "Jika kamu butuh bantuan, minta developer untuk memastikan GoWA sudah online dan token QR tersedia.", en: "If you need help, ask the developer to ensure GoWA is online and QR tokens are available." },
  "whatsapp.noQrHint": { id: "Tidak ada QR code? Gunakan link di atas atau hubungi developer.", en: "No QR code? Use the link above or contact the developer." },
  "whatsapp.phoneRequired": { id: "Nomor WhatsApp tidak boleh kosong.", en: "WhatsApp number cannot be empty." },
  "whatsapp.saveSuccess": { id: "Nomor WhatsApp tersimpan. Kembali ke dashboard untuk melihat koneksi.", en: "WhatsApp number saved. Return to the dashboard to view connections." },
  "whatsapp.saveError": { id: "Gagal menyimpan koneksi WhatsApp.", en: "Failed to save WhatsApp connection." },
  "whatsapp.copySuccess": { id: "URL GoWA berhasil disalin ke clipboard.", en: "GoWA URL copied to clipboard." },
  "whatsapp.copyError": { id: "Gagal menyalin URL ke clipboard.", en: "Failed to copy URL to clipboard." },
  "whatsapp.details1": { id: "Scan QR code di GoWA untuk menghubungkan akun WhatsApp kamu ke sistem.", en: "Scan the QR code in GoWA to connect your WhatsApp account to the system." },
  "whatsapp.details2": { id: "Setelah terhubung, simpan nomor WhatsApp yang akan digunakan untuk penjadwalan pesan.", en: "After connecting, save the WhatsApp number to be used for message scheduling." },
  "whatsapp.details3": { id: "Jika GoWA belum dikonfigurasi, hubungi developer untuk mengatur GOWA_BASE_URL.", en: "If GoWA is not configured, contact the developer to set up GOWA_BASE_URL." },

  // Common
  "common.search": { id: "Cari...", en: "Search..." },
  "common.settings": { id: "Pengaturan", en: "Settings" },
  "common.darkMode": { id: "Mode Gelap", en: "Dark Mode" },
  "common.lightMode": { id: "Mode Terang", en: "Light Mode" },
  "common.language": { id: "Bahasa", en: "Language" },
  "common.loading": { id: "Memuat...", en: "Loading..." },
  "common.success": { id: "Berhasil!", en: "Success!" },
  "common.error": { id: "Terjadi kesalahan", en: "An error occurred" },
  "common.cancel": { id: "Batal", en: "Cancel" },
  "common.save": { id: "Simpan", en: "Save" },
  "common.confirm": { id: "Konfirmasi", en: "Confirm" },
  "common.close": { id: "Tutup", en: "Close" },
  "common.yes": { id: "Ya", en: "Yes" },
  "common.no": { id: "Tidak", en: "No" },
  "common.delete": { id: "Hapus", en: "Delete" },

  // Footer
  "footer.tagline": { id: "Platform AI Pemasaran Konten Terpadu", en: "Integrated AI Content Marketing Platform" },
  "footer.rights": { id: "Hak cipta dilindungi.", en: "All rights reserved." },

  // Profile additions
  "profile.formatNotSupported": { id: "Format tidak didukung. Gunakan JPG, PNG, WebP, atau GIF.", en: "Format not supported. Use JPG, PNG, WebP, or GIF." },
  "profile.fileTooLarge": { id: "Ukuran file terlalu besar. Maks 5 MB.", en: "File too large. Max 5 MB." },
  "profile.uploadFailed": { id: "Gagal mengupload foto.", en: "Failed to upload photo." },
  "profile.errorTryAgain": { id: "Terjadi kesalahan. Coba lagi.", en: "An error occurred. Please try again." },
  "profile.uploading": { id: "Mengupload…", en: "Uploading…" },
  "profile.savePhoto": { id: "Simpan Foto", en: "Save Photo" },
  "profile.changePhoto": { id: "Ganti foto profil", en: "Change profile photo" },
  "profile.photoUpdated": { id: "✓ Foto profil berhasil diperbarui!", en: "✓ Profile photo updated successfully!" },
  "profile.namePlaceholder": { id: "Masukkan nama lengkap", en: "Enter your full name" },
  "profile.phonePlaceholder": { id: "+62 812-3456-7890", en: "+62 812-3456-7890" },
  "profile.videosCreated": { id: "VIDEO DIBUAT", en: "VIDEOS CREATED" },
  "profile.platformsConnected": { id: "PLATFORM TERHUBUNG", en: "PLATFORMS CONNECTED" },

  // Video AI share platform names
  "videoAi.twitter": { id: "Twitter / X", en: "Twitter / X" },
  "videoAi.instagram": { id: "Instagram", en: "Instagram" },
  "videoAi.facebook": { id: "Facebook", en: "Facebook" },

  // Image AI share platform names
  "imageAi.twitter": { id: "Twitter / X", en: "Twitter / X" },
  "imageAi.instagram": { id: "Instagram", en: "Instagram" },
  "imageAi.facebook": { id: "Facebook", en: "Facebook" },


  // Auto Upload - coming soon dialog
  "autoUpload.statusConnection": { id: "Status Koneksi", en: "Connection Status" },
  "autoUpload.comingSoonIntegration": { id: "Integrasi {platform} belum tersedia dalam versi ini.", en: "{platform} integration is not available in this version yet." },
  "autoUpload.roadmapNote": { id: "Platform ini ditampilkan untuk keperluan roadmap. Silakan gunakan Instagram, Facebook, atau platform lain yang sudah terhubung.", en: "This platform is shown for roadmap purposes. Please use Instagram, Facebook, or other connected platforms instead." },

  // Member
  "member.contactPhone": { id: "0819-9990-0900", en: "0819-9990-0900" },

  // Content Analytics - sentiment labels
  "analytics.sentimentPositive": { id: "Positif", en: "Positive" },
  "analytics.sentimentNeutral": { id: "Netral", en: "Neutral" },
  "analytics.sentimentNegative": { id: "Negatif", en: "Negative" },

  // Content Analytics - error & chart
  "analytics.generateFailed": { id: "Gagal generate strategi", en: "Failed to generate strategy" },
  "analytics.engagementRate": { id: "Engagement Rate", en: "Engagement Rate" },
  "analytics.estReachChart": { id: "Est. Reach", en: "Est. Reach" },

  // Content Analytics - audience options
  "analytics.audienceGenZ": { id: "Gen Z (13–24)", en: "Gen Z (13–24)" },
  "analytics.audienceMillennial": { id: "Millennial (25–34)", en: "Millennial (25–34)" },
  "analytics.audienceProfessional": { id: "Profesional (30–45)", en: "Professional (30–45)" },
  "analytics.audienceHousewife": { id: "Ibu rumah tangga", en: "Housewives" },
  "analytics.audienceStudent": { id: "Pelajar / Mahasiswa", en: "Students / College" },
  "analytics.audienceGeneral": { id: "Umum", en: "General" },

  // Content Analytics - content type options
  "analytics.contentTypeProductLaunch": { id: "Produk launch", en: "Product Launch" },
  "analytics.contentTypeEdu": { id: "Edukasi / Tutorial", en: "Education / Tutorial" },
  "analytics.contentTypeEntertainment": { id: "Entertainment / Hiburan", en: "Entertainment" },
  "analytics.contentTypeBts": { id: "Behind the scenes", en: "Behind the scenes" },
  "analytics.contentTypeUgc": { id: "User-generated content", en: "User-generated content" },
  "analytics.contentTypePromo": { id: "Promosi / Diskon", en: "Promo / Discount" },
  "analytics.contentTypeInspirational": { id: "Inspirational / Motivasi", en: "Inspirational / Motivation" },

  // Auto Upload - error
  "autoUpload.serverError": { id: "Terjadi kesalahan pada server", en: "An error occurred on the server" },
}

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("id")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const savedLang = localStorage.getItem("carubra-language") as Language
    if (savedLang && (savedLang === "id" || savedLang === "en")) {
      setLanguage(savedLang)
    }
  }, [])

  useEffect(() => {
    if (mounted) {
      localStorage.setItem("carubra-language", language)
      document.documentElement.lang = language
    }
  }, [language, mounted])

  const t = (key: string, params?: Record<string, string | number>): string => {
    const translation = translations[key]
    if (!translation) {
      if (process.env.NODE_ENV === "development") {
        console.warn(`[i18n] Missing translation key: "${key}"`)
      }
      return key
    }
    let text = translation[language]
    if (params) {
      text = text.replace(/\{(\w+)\}/g, (_, paramName) => String(params[paramName] ?? ""))
    }
    return text
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
